{{- if .Values.acrCredentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grupo118fase4.fullname" . }}-acr-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{"%s":{"username":"%s","password":"%s","auth":"%s"}}}` .Values.acrCredentials.registry .Values.acrCredentials.username .Values.acrCredentials.password (printf "%s:%s" .Values.acrCredentials.username .Values.acrCredentials.password | b64enc) | b64enc }}
{{- end }}
